<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\Books\Controllers\BooksController;
use Illuminate\Support\Facades\Route;

Route::post('books/books', [BooksController::class, 'create']);
Route::get('books/books/{id}', [BooksController::class, 'get']);
