<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\Books\Controllers\BooksController;
use App\Http\ApiV1\Modules\News\Controllers\BooksController as BooksController2;
use Illuminate\Support\Facades\Route;

Route::post('news/news', [BooksController::class, 'create']);
Route::get('news/news/{id}', [BooksController2::class, 'get']);
